version: "3.3"
services:
  kalico_backend:
    image: 537408061242.dkr.ecr.us-east-2.amazonaws.com/kalico:backend
    container_name: kalico_backend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kalico_backend.rule=Host(`api.kalico.ai`)"
      - "traefik.http.routers.kalico_backend.service=kalico_backend"
      - "traefik.http.services.kalico_backend.loadbalancer.server.port=8080"
    networks:
      - traefik_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /tmp:/tmp
networks:
  traefik_network:
    external: true

