version: "3.3"
services:
  foodwallah_blog_ui:
    image: 537408061242.dkr.ecr.us-east-2.amazonaws.com/mere-recipes:mere_recipes-prod-blog-ui-latest
    container_name: foodwallah_blog_ui
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foodwallah_blog_ui.rule=Host(`foodwallah.com`, `www.foodwallah.com`)"
      - "traefik.http.routers.foodwallah_blog_ui.service=foodwallah_blog_ui"
      - "traefik.http.services.foodwallah_blog_ui.loadbalancer.server.port=3000"
    networks:
      - traefik_network

networks:
    traefik_network:
      external: true

